name: se local action runner test

on:
  push:
    branches:
      - dev
jobs:
  test-job:
    runs-on: [self-hosted, windows]
    steps:
      - name: 测试环节
        run: echo "Hello! This is running on my local Windows runner 🎉"
